feat: DataVpc construct
awslabs/data-solutions-framework-on-aws pull request #283
Opened 2023-12-07 08:44 UTC by vgkowski

**Issue #, if available:**

## Description of changes:

Add a new construct for creating a standard VPC for data platforms including VPC flow logs in CLoudWatch log group and S3 VPC endpoint

**Checklist**

 

* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-07 16:21 UTC, vgkowski commented
I have ran the e2e test that failed because of exceeded quota and it passed

2023-12-07 18:19 UTC, lmouhib requested changes
few minor comments

2023-12-07 18:19 UTC, lmouhib commented on framework/src/utils/lib/data-vpc-props.ts
> +  readonly flowLogRole?: IRole;
can you please update to specify which principal should be supplied to the role for it to be assumed correctly by AWS?

https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-cwl.html#flow-logs-iam-role

2023-12-07 18:19 UTC, lmouhib commented on framework/src/utils/lib/data-vpc-props.ts
> +   */
Can you add a note to ask the user to add a resource policy to the key to allow its use by the flow log?

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html

2023-12-07 18:19 UTC, lmouhib commented on framework/src/utils/lib/data-vpc-props.ts
> +   * @default - RETAIN (The bucket will be orphaned).
remove this or change it to log "(The bucket will be orphaned)"

2023-12-07 18:19 UTC, lmouhib commented on framework/src/utils/lib/data-vpc.ts
> +   * The S3 VPC endpoint
VPC endpoint gateway

2023-12-08 16:13 UTC, lmouhib approved these changes
LGTM

2023-12-08 16:14 UTC, merged