Feat: data copy
awslabs/data-solutions-framework-on-aws pull request #292
Opened 2023-12-12 14:39 UTC by vgkowski

**Issue #, if available:**

## Description of changes:

Add `S3DataCopy` construct to copy data from a source bucket to a destination bucket during CDK deploy time

**Checklist**

 

* [x] Update tests
* [] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-12 18:01 UTC, lmouhib requested changes

2023-12-12 18:01 UTC, lmouhib commented on framework/src/utils/lib/s3-data-copy.ts
> +    new CustomResource(this, 'CustomResource', {
can you add the parameter called `resourceType` and provide a value as follow 'DSF::S3DataCopy::Copy'. This is for visibility on the custom resource in the CFN console

2023-12-13 15:13 UTC, balabad commented on framework/src/utils/lib/s3-data-copy.ts
> +        TARGET_BUCKET_PREFIX: props.targetBucketPrefix || '',
The character here is not a space but a "no-break space NBSP" (Unicode U+00A0). We shouldn't use special characters in code.
```suggestion
        TARGET_BUCKET_PREFIX: props.targetBucketPrefix || '',
```

2023-12-13 19:58 UTC, lmouhib approved these changes

2023-12-14 07:56 UTC, merged