feat: Opensearch construct
awslabs/data-solutions-framework-on-aws pull request #374
Opened 2024-01-24 16:55 UTC by alexvt-amz

**Issue #, if available:**
203 

## Description of changes:

Opensearch construct

**Checklist**

 

* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-30 10:32 UTC, lmouhib requested changes
Can you please move the construct under a new directory called `consumption`

2024-01-30 13:59 UTC, alexvt-amz commented
> Can you please move the construct under a new directory called `consumption`

done

2024-02-06 09:43 UTC, sharp-pixel commented
Can we rename `Opensearch` to `OpenSearch`?

2024-02-08 21:20 UTC, lmouhib commented
> Can we rename `Opensearch` to `OpenSearch`?

@sharp-pixel where ? in the documentation? or Construct name? or everywhere where the uppercase is compliant?

2024-02-08 22:43 UTC, sharp-pixel commented
> > Can we rename `Opensearch` to `OpenSearch`?
> 
> @sharp-pixel where ? in the documentation? or Construct name? or everywhere where the uppercase is compliant?

Everywhere where it doesn't break something.
Examples:
- names: `OpensearchNodes` -> `OpenSearchNodes`
- comments: Default Node Instances for Opensearch cluster -> Default Node Instances for OpenSearch cluster

2024-02-09 22:30 UTC, alexvt-amz commented
> > > Can we rename `Opensearch` to `OpenSearch`?
> > 
> > 
> > @sharp-pixel where ? in the documentation? or Construct name? or everywhere where the uppercase is compliant?
> 
> Everywhere where it doesn't break something. Examples:
> 
> * names: `OpensearchNodes` -> `OpenSearchNodes`
> * comments: Default Node Instances for Opensearch cluster -> Default Node Instances for OpenSearch cluster

Fixed

2024-02-19 21:24 UTC, vgkowski requested changes

2024-02-19 21:24 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch-props.ts
> +  readonly samlMasterBackendRole:string;
strong type => IRole or Role

2024-02-19 21:24 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch-props.ts
> +  readonly encryptionKmsKeyArn?:string;
strong type => IKey or Key

2024-02-19 21:24 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch.ts
> + *    const osCluster = new dsf.consumption.OpensearchCluster(this, 'MyOpensearchCluster',{
reindent on the left

2024-02-19 21:24 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch.ts
> +   * @public
@public unnecessary

2024-02-19 21:24 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch.ts
> +   * Cloudwatch log group to store OpenSearch cluster logs
=> CloudWatch Logs Log Group

2024-02-19 21:24 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch.ts
> +   * OpenSearchCluster domain
=> OpenSearch Cluster Domain

2024-02-19 21:24 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch.ts
> +      trackingTag: id,
=> trackingTag: OpenSearchCluster.name

2024-02-19 21:24 UTC, vgkowski commented on framework/test/unit/consumption/opensearch.test.ts
> +
Missing tests for extra methods based on custom resource

2024-02-21 09:02 UTC, vgkowski requested changes

2024-02-21 09:02 UTC, vgkowski commented on framework/src/consumption/lib/opensearch/opensearch-props.ts
> +  readonly vpc?: IVpc;
Subnets are missing

2024-02-27 18:21 UTC, vgkowski approved these changes

2024-02-27 18:23 UTC, lmouhib approved these changes

2024-02-27 18:23 UTC, merged