fix: opensearch api
awslabs/data-solutions-framework-on-aws pull request #500
Opened 2024-03-22 13:11 UTC by alexvt-amz

IAM role permission fixed, added support for multiple HTTP menthods for Opensearch API

2024-03-25 16:39 UTC, lmouhib requested changes
Few minor changes/comment.

I am ok with this change, however we need to make sure we communicate the changes on the methods, although these are minor.

2024-03-25 16:39 UTC, lmouhib commented on examples/opensearch-quickstart/stacks/main.py
> +class OpenSearchStack(Stack):
Can you add some comments between the method you call, just to make it more readable.

2024-03-25 16:39 UTC, lmouhib commented on framework/src/consumption/lib/opensearch/opensearch.ts
> +      removalPolicy: this.removalPolicy,
We need to be careful here, can you add this as a parameter? This is a hidden behavior for the user, we need to give them the ability to either retain or delete on a per resource level when it comes to these calls.

2024-03-25 16:39 UTC, lmouhib commented on framework/src/consumption/lib/opensearch/opensearch.ts
> +      backend_roles: rolesToPersist,
Once you address the removal policy, i would suggest to keep this on `DELETE`

2024-03-25 16:39 UTC, lmouhib commented on framework/src/consumption/lib/opensearch/resources/lambda/opensearch-api/opensearch-api.mjs
>    const secretsResolvedBody = await resolveSecrets(body);
What is the timeout of the CR here? we might want to put it for some long time (maybe few minutes?) in case a user pass a big payload.

2024-03-26 17:49 UTC, vgkowski approved these changes

2024-03-26 19:25 UTC, lmouhib approved these changes

2024-03-26 19:26 UTC, merged