Fix/os example
awslabs/data-solutions-framework-on-aws pull request #516
Opened 2024-03-27 12:24 UTC by alexvt-amz

fix opensearch example and lerna build

2024-03-27 12:26 UTC, lmouhib approved these changes

2024-03-27 12:31 UTC, vgkowski commented
Can you add a readme to explain how to deploy this? Especially the SAML prerequisite and the XML file to configure...

2024-03-27 12:31 UTC, vgkowski requested changes
We need a readme file to explain how to deploy (similar to the spark data lake example)

2024-03-28 19:29 UTC, vgkowski approved these changes

2024-03-28 19:30 UTC, merged