fix: opensearch api as separate construct
awslabs/data-solutions-framework-on-aws pull request #694
Opened 2024-07-27 16:39 UTC by alexvt-amz

**Issue #, if available:**

## Description of changes:

**Checklist**

 

* [ ] Update tests
* [ ] Update docs
* [ ] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-16 10:14 UTC, lmouhib requested changes

2024-08-19 14:42 UTC, alexvt-amz commented on framework/src/consumption/lib/opensearch/opensearch-api.ts
> +export class OpenSearchApi extends TrackedConstruct {
we don;t create them in the API, we create those in the cluster itself... or you want those that exposed in the cluster construct to have also exposed in the api construct?

2024-08-25 17:04 UTC, lmouhib requested changes

2024-08-25 17:04 UTC, lmouhib commented on framework/src/consumption/lib/opensearch/opensearch.ts
> -   * CDK Custom resource provider for calling OpenSearch APIs
Can you expose the resource created by the DSFProvider from the opensearch api construct.

2024-08-25 17:04 UTC, lmouhib commented on website/docs/constructs/library/generated/_consumption-opensearch.mdx
> +    const osCluster = new dsf.consumption.OpenSearchCluster(this, 'MyOpenSearchCluster',{
Can you also add a documentation page for the API, call it `Opensearch API - Bring your own Opensearch cluster`.

2024-09-03 12:49 UTC, alexvt-amz commented on framework/src/consumption/lib/opensearch/opensearch-api-props.ts
> +  readonly subnets?: SubnetSelection;
we need it as options as it can be a public cluster.

2024-09-15 16:32 UTC, lmouhib requested changes
Need a fix for license headers

2024-09-15 16:32 UTC, lmouhib commented on framework/src/consumption/lib/opensearch/opensearch.ts
>  // SPDX-License-Identifier: MIT-0
Can you change this to Apache 2.0

2024-09-26 16:39 UTC, lmouhib requested changes
few things to change in the documentation.

2024-09-26 16:39 UTC, lmouhib commented on framework/src/consumption/examples/opensearch-api.lit.ts
>      const osCluster = new dsf.consumption.OpenSearchCluster(this, 'MyOpenSearchCluster',{
Can you change this to how the construct should be initialized, and not testing it through the openseach cluster construct. We have an example on kafka-api unit tests `kafka-api.test.ts`

2024-09-26 16:39 UTC, lmouhib commented on framework/src/consumption/README.md
> +[example OpenSearch API](examples/opensearch-api.lit.ts)
Can you provide a dummy example without initializing the actual OS cluster with construct, but provide how to initialize the OS-api construct.

2024-09-26 16:39 UTC, lmouhib commented on framework/src/consumption/README.md
> +```typescript
Can you provide this through an example lit file.

2024-11-19 09:14 UTC, lmouhib approved these changes

2024-11-19 09:17 UTC, merged