feat: add encryption key to lambda environment
awslabs/data-solutions-framework-on-aws pull request #768
Opened 2024-10-22 16:43 UTC by mehdimld

**Issue #, if available:** #754 

## Description of changes:

This PR builds upon the changes in #756 and adds environmentEncryption property to all the lambdas deployed by the KafkaAPI.

**Checklist**

 

* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-22 18:23 UTC, lmouhib requested changes
Can you add the same for msk-provisioned props and construct?

2024-10-23 07:44 UTC, armaseg commented
Could you please add in the `framework/src/streaming/README.md` how we could use this feature and what is encrypted?

2024-10-24 09:49 UTC, armaseg approved these changes
Thanks for the contribution

2024-11-01 11:36 UTC, lmouhib approved these changes

2024-11-01 11:37 UTC, merged