feat: add lake formation support in catalog
awslabs/data-solutions-framework-on-aws pull request #810
Opened 2024-11-29 09:19 UTC by vgkowski

**Issue #, if available:**

## Description of changes:

Add the support for Lake Formation permission model in the `DataCatalogDatabase` and the `DataLakeCatalog` constructs. Supports both full and hybrid mode.

**Checklist**

 

* [x] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/) (`fix: `, `feat: `, `docs: `, ...)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-02-07 14:42 UTC, lmouhib requested changes

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database-props.ts
> +  readonly lakeFormationDataAccessRole?: IRole;
Can you be more explicit here? Who will assume this role? What is its principal? Lakeformation, Glue, Cloudformation?

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database-props.ts
> +  readonly lakeFormationConfigurationRole?: IRole;
Can you be more explicit here? Who will assume this role? What is its principal? Lakeformation, Glue, Cloudformation?

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +import { /*grantDataLakeLocation,*/ grantCrawler, grantDataLakeLocation, putDataLakeSettings, registerS3Location, revokeIamAllowedPrincipal } from './lake-formation-helpers';
can you clean this `grantDataLakeLocation` its commented out.

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +  readonly lfDataAccessRole?: IRole;
Please be more explicit in the variable naming, I understand `lf` means lakeformation, but we need to reflect it in the variable name.

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +  readonly crawlerLfLocationGrant?: CfnPrincipalPermissions;
Same on Lf

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +  readonly crawlerLfDbGrant?: CfnPrincipalPermissions;
Same on Lf anf Db

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +  readonly crawlerLfTablesGrant?: CfnPrincipalPermissions;
Same on Lf

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +  readonly lfRevokeRole?: IRole;
Same on lf

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +  readonly cdkLfLocationGrant?: CfnPrincipalPermissions;
Can you clarify this is only available when using lakeformation, is it also the case for hybrid?

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +    const useLakeFormation = props.permissionModel === PermissionModel.LAKE_FORMATION || props.permissionModel === PermissionModel.HYBRID;
can you first if the value exist? instead of this being implicit. Meaning use `props?.`

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +      if (props.permissionModel === PermissionModel.LAKE_FORMATION) {
Why a nested condition? please lets remove the nested condition and check this on line 180 too.

2025-02-07 14:42 UTC, lmouhib commented on framework/src/governance/lib/data-lake-catalog-props.ts
> +  readonly lakeFormationDataAccessRole?: IRole;
same as the comment in the datalog datatabse props.

2025-02-07 15:30 UTC, lmouhib requested changes

2025-02-10 15:46 UTC, vgkowski commented on framework/src/governance/lib/data-catalog-database.ts
> +  readonly cdkLfLocationGrant?: CfnPrincipalPermissions;
not needed anymore

2025-02-12 09:01 UTC, lmouhib requested changes

2025-02-12 09:01 UTC, lmouhib commented on framework/src/governance/lib/data-catalog-database.ts
> +  private static readonly DEFAULT_PERMISSION_MODEL = PermissionModel.IAM;
Can you throw an error if the permission model is IAM but the user pass the roles for lakeformation.

2025-02-12 13:16 UTC, lmouhib approved these changes

2025-02-12 13:16 UTC, merged